# Generated by Django 4.2.27 on 2026-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_remove_customer_created_at_alter_customer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avatar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
